version: '3'
services:
  nodejs-template:
    build: ./
    ports:
      - '4000:4000'
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - ./package.json:/app/package.json
    depends_on:
      - db
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_URI: ${DATABASE_URL}
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  dbdata:
